In [ ]:
from numpy import *
arr = array([])
for i in range(5):
  v = input("Element: ")
  arr = append(arr, v)
print(arr)

Element: 1
Element: 5
Element: 6
Element: 88
Element: 66
['1' '5' '6' '88' '66']


In [ ]:
import numpy as np
arr1d = np.array([1,2,3])
print(arr1d)

arr2d = np.array([[1, 2], [3, 4]])
print(arr2d)


[1 2 3]
[[1 2]
 [3 4]]


In [ ]:
#0array

zeroarr = np.ones((2,3))
print(zeroarr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#0array

zeroarr = np.zeros((2,3))
print(zeroarr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.array([1,2,3], dtype = 'float32')
print(arr)

[1. 2. 3.]


In [ ]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
#indexing

arr = np.array([10,20,30,40])
print(arr[1])

arr2d = np.array([[10,20],[30,40]])
print(arr2d[1,1])


20
40


In [ ]:


arr = np.array([[10,20],[30,40]])
print(arr[:1])
print(arr[:0])

[[10 20]]
[]


In [ ]:
#boolean indexing

arr = np.array([10,20,30,40])
print(arr[arr>=20])

[20 30 40]


In [ ]:
#reshape

arr = np.arange(6)
print(arr)

reshaped = arr.reshape(2,3)
print(reshaped)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [ ]:
#stacking

a = np.array([1,2])
b = np.array([3,4])

v = np.vstack((a,b))
h = np.hstack((a,b))

print(v)
print(h)

[[1 2]
 [3 4]]
[1 2 3 4]


In [ ]:
#splitting

arr = np.arange(6).reshape(2,3)
print(arr)

print('\n')

print('ABBC')

print('\n')

print(np.hsplit(arr, 3))

[[0 1 2]
 [3 4 5]]


ABBC


[array([[0],
       [3]]), array([[1],
       [4]]), array([[2],
       [5]])]


In [ ]:
#Problem 1: Create a NumPy array from the Python list [5,10,15,20,25]. Print the array.

a = np.array([5,10,15,20,25])
print(a)

[ 5 10 15 20 25]


In [ ]:
#Problem 2: Create a 2D NumPy array from the Python list [[1,2],[3,4],[5,6]] and print it.

a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#Problem 3: Create a 3x3 matrix of zeros using NumPy. Print the matrix.

zeroarr = np.zeros((3,3))
print(zeroarr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Problem 4: Use np.arange() to create a NumPy array with values from 10 to 100, with a step of 10. Print the array.

arr = np.arange(10,101, 10)
print(arr)


[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
#Problem 5: Create a NumPy array filled with ones, with shape (4,2). Print the array.

a = np.ones((4,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Problem 6: Create a 1D NumPy array of 10 evenly spaced values between 1 and 100 using np.linspace(). Print the array.

a = np.linspace(1, 101, 10)
print(a)

[  1.          12.11111111  23.22222222  34.33333333  45.44444444
  56.55555556  67.66666667  78.77777778  89.88888889 101.        ]


In [ ]:
#Problem 7: Convert the Python list [3,6,9] to a NumPy array and perform element-wise multiplication by 3. Print the result.

array = np.array([3,6,9])
new_array = array *3
print(new_array)

[ 9 18 27]


In [ ]:
#Problem 8: Create a 2D array a = [[1,2],[3,4]] and access the element at row 1, column 0. Print the element.

a = np.array([[1,2],[3,4]])
print(arr2d[1,0])

3


In [ ]:
#Problem 9: Slice the array a = [2,4,6,8,10] to extract the first three elements. Print the result.

arr = np.array([2,4,6,8,10])
print(arr[:3])


[2 4 6]


In [ ]:
#Problem 10: Create a 1D array of size 10 filled with random integers between 1 and 100 using np.random.randint(). Print the array.

a = np.random.randint(1,101, 10)
print(a)

[43 95 34 72 80 87 52 29 49  8]
